apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wallon-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
